### ISSUE TITLE
Can we merge app.json & app.config.ts?

### ISSUE THREAD

**Issue by floatplane** [stevekuznetsov/avalanche-forecast#10]
These both serve the same purpose: https://docs.expo.dev/workflow/configuration/

The JSON file is read in and then app.config.ts modifies it - but is it actually helpful to have this spread across 2 source files?

**Comment by stevekuznetsov** [comment]
Yes, the TypeScript file dynamically loads secret data from environment and injects it - I don't think there's a static way to do do that. If you can find it, I'd love to remove the TypeScript, as it breaks a lot of Expo's developer experience bits.

**Comment by floatplane** [comment]
Oh, I didn’t realize there was a downside to `app.config.ts` from a DX perspective - what does it break?

TBH I wrote this issue with the perspective of “why don’t we just move _everything_ into app.config.ts, since we can’t put the dynamic bits into a JSON file?”. But it sounds like there’s a good reason to keep as much as possible in the JSON file, in which case maybe I’ll just close this issue.

**Comment by stevekuznetsov** [comment]
Ah gotcha - yeah all of the `expo` CLI steps that would have otherwise dynamically injected config into your JSON fall over with an error instead when you have a TS config file.
