### ISSUE TITLE
Handle the wind speed asterisk case

### ISSUE THREAD

**Issue by floatplane** [stevekuznetsov/avalanche-forecast#109]
I noticed this was a possibility when scraping but punted on it because I had no idea what it was. It's totally undiscoverable.

On the [mountain weather forecast page](https://nwac.us/mountain-weather-forecast/), sometimes the time periods like "Saturday Night" have an asterisk next to them. Good luck looking for a footnote on the table or on the page! But if you roll over the tooltip and manage to read through a really long chunk of text, then you'll unlock the key:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/101196/215163478-709ca8b3-73c9-461b-bc07-732ca0d89b4a.png">

This is one of those things that I'm sure never had design eyes on it, but we'll probably need to display this information in some way. I'm not going to mess with the HTML scraper, but the JSON api should account for surfacing this in some way. cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
Ha! I've actually seen this & had to figure it out on the website in the past couple years. Lets 100% get some design brains on it!
