### ISSUE TITLE
Disable specific mission ridge weather station

### ISSUE THREAD

**Issue by floatplane** [stevekuznetsov/avalanche-forecast#132]
I asked in slack:

> The mission ridge data table (https://nwac.us/weatherdata/missionridge/now/) only shows wind speed measurements for the highest elevation station, though the API shows there are wind measurements available at lower elevations. Is that an intentional omission, i.e. are people most interested in wind behavior higher up and so that’s what we choose to display?

Dennis replied in email:

> Ha! There is a secret wind station at the base of Mission. It shouldn't be in our API because we don't use it/look at it and I don't even know if it's reporting.  It's not useful for avalanche forecasting at those elevations or location in the terrain. I'm not sure why it was ever installed, a before my time piece. 
> 
> It's on the top of the bullwheel for the base chair (picture attached) and really just needs to be pulled since no one is using it.  Hopefully we can clean that up from API/DB at some point...

- [ ] figure out, do we want to keep other readings from this station (temp etc) or just disable it entirely?
- [ ] should the weather station be disabled on the NWAC side, so that the data doesn't get piped to snowbound? it shows up in snowbound as normal

**Comment by floatplane** [comment]
@charlotteguard tracking the mystery of the Mission Ridge Weather Station over here 👻

**Comment by stevekuznetsov** [comment]
Having center-specific call-outs to ignore otherwise present data from SnowBound is fairly fragile - if it's an equal amount of work, having it disabled at the SnowBound side would be ideal.

**Comment by stevekuznetsov** [comment]
@floatplane we had this fixed at the DB layer, right?

**Comment by floatplane** [comment]
Ah yeah, Dennis fixed this by removing the weather station from the API!
