### ISSUE TITLE
Look at logging errors from data fetching (`useMapLayer`, etc)

### ISSUE THREAD

**Issue by floatplane** [stevekuznetsov/avalanche-forecast#15]
There's a couple of error paths:
- network failure
- data validation

Figure out the right way to deal with both

**Comment by stevekuznetsov** [comment]
@floatplane now that we fetch stuff at the top and not within the polygon, do we ever have a case where we can't show an error modal or screen anymore?

**Comment by floatplane** [comment]
I don't think so! I think my concern here was more about logging errors to the backend. Network errors probably aren't that interesting - they should just bubble up to the user.

We do want to make sure that we log to Sentry anytime we applying data validation rules and they fail. That would indicate a potentially unexpected change on the backend. We definitely do this in some places but I'm not sure if we do it everywhere...

**Comment by stevekuznetsov** [comment]
Handled this in #287

**Comment by stevekuznetsov** [comment]
Oops, was in https://github.com/stevekuznetsov/avalanche-forecast/pull/286
