### ISSUE TITLE
Forecast forecast experience flow doesnt work as expected

### ISSUE THREAD

**Issue by yuliadub** [stevekuznetsov/avalanche-forecast#159]
When I first open the app and I am navigating to weather data from home (map) view before selecting a zone, that works as expected, I see the list of all regions and weather stations and I can select a weather station and then go back to the list. 

however, if next I select a a specific zone, then click on the weather tab at the top, and then select a weather station (in my case snoqualmie region, alpental weather station), when I click the back button, it takes me to the list of all stations so I am no longer in the specific region view. 

alternatively, if I first open the app and first navigate to a specific zone (and not the weather data tab), when I go back I am taken to the region specific weather tab, however now if I go back to home (the map) and then navigate to weather data, I can no longer see the weather region/station list (there is no way for me to get to it as far as I can tell), it takes me to the specific weather station I just viewed, and if I push back I end up on the home page with the region of the station pre-selected. 

happy to provide a video if that'd be helpful!

**Comment by stevekuznetsov** [comment]
Both of these reproduce for me.

@floatplane it look like when we go into weather data from the weather tab in the avalanche forecast, we end up inside of the navigation stack for the weather data bottom tab navigator, and on the face of it I think those two stacks could/should be entirely separate?

**Comment by floatplane** [comment]
the first one does not repro for me, do I have the scenario correct?

https://user-images.githubusercontent.com/101196/220443323-acab3e66-af76-4073-afb3-1283e7128733.mp4

**Comment by floatplane** [comment]
@yuliadub are you testing the latest in Expo Go, or is this with a TestFlight build?

**Comment by floatplane** [comment]
ah now I understand, you actually have to visit the weather station list first. hmm that's an odd one 🤔 

@stevekuznetsov there are indeed multiple stacks, let's say you go through the following sequence:
1. tap weather data, choose Blewett Pass (don't press back)
2. tap "Home", tap "Snoqualmie Pass", tap "Weather" tab
3. tap "Alpental Ski Area"

then you end up in a state like this

```
                alpental
snoq forecast   blewett pass
map view        weather station list
--------------  --------------------
home stack      weather data stack
```
and the default behavior of the `back()` function is to keep popping your current stack before changing any stacks

**Comment by floatplane** [comment]
I am inclined to say that the cross-stack navigation from the weather forecast to the weather station data should just clean out the existing weather data stack first. would that break anything?

**Comment by stevekuznetsov** [comment]
Hm..... is it possible to have more than one instance of the weather data stack?

**Comment by stevekuznetsov** [comment]
Looks like no. @floatplane would there be any downside to just having a second (distinct) stack with the same screens inside of it?

**Comment by floatplane** [comment]
based on a quick couple of minutes playing with Slack, seems like the solution that feels right is to never switch stacks except via the tabs at the bottom (try it yourself by choosing to DM someone from the "DM" tab vs from the Home screen). 

so in this particular scenario, we'd want to push "Alpental Ski Area" onto the home stack.

I don't think a second distinct stack would necessarily be helpful, probably makes the mental model even more confusing for users.

**Comment by floatplane** [comment]
@yuliadub i haven’t touched this but will try to resolve it today - @stevekuznetsov and I talked about a plan for improving this. Thanks for the detailed scenarios, those will be very helpful!
