### ISSUE TITLE
Observation Filter Toggle Colors Off

### ISSUE THREAD

**Issue by stevekuznetsov** [stevekuznetsov/avalanche-forecast#261]
Compare the toggles in the observation filter:

![IMG_0093](https://user-images.githubusercontent.com/7328370/226409887-ef90e6d5-62f5-4ceb-b6df-7a3edc6b3a08.jpg)

To those in the observation submit form:

![IMG_0092](https://user-images.githubusercontent.com/7328370/226409937-611fb16d-1cea-4d50-a9c7-b9f4c04592b5.jpg)

**Comment by floatplane** [comment]
Sorry just saw this - no idea offhand! If you want to assign to me, I can look on Saturday.
