### ISSUE TITLE
Padding on travel advice cut off for some danger ratings 

### ISSUE THREAD

**Issue by charlotteguard** [stevekuznetsov/avalanche-forecast#264]
The padding for the travel advice (click on a zone from a home screen before clicking into the full forecast) - none of the words are cut off so it's not a readability issue - just from a looks perspective. 

![IMG_5359](https://user-images.githubusercontent.com/119702342/228381839-90083ca8-7775-48a0-a202-918ef6f80de7.png)
![IMG_5317](https://user-images.githubusercontent.com/119702342/228381847-89976770-f4bf-4cde-b765-03134d54189b.PNG)

**Comment by yuliadub** [comment]
also have seen this in avalanche warning card too

![image](https://user-images.githubusercontent.com/9418602/228615858-c075acf1-9be6-476a-b6a5-0bde80f01be9.png)

**Comment by stevekuznetsov** [comment]
@yuliadub ah, that's just me being bad at coding - separate from the other issue, will fix
