### ISSUE TITLE
Olympic region gets selected by default when app opens

### ISSUE THREAD

**Issue by yuliadub** [stevekuznetsov/avalanche-forecast#272]
this happens even after the app is killed and reopened. Creates an inconsistent experience where it is confusing when app sometimes opens and region is not selected, and then other times it opens that Olympic region is selected.

link to video:  https://nwactechcommittee.slack.com/archives/C051KR96B2L/p1680110640360609

**Comment by stevekuznetsov** [comment]
A simple reproducer for this:

1. start the app, see the correct map screen (no zone selected)
2. navigate to the observations tab
3. navigate back to the map
4. see the Olympics selected

I've debugged down to seeing that our `handleScroll` fires: 

https://github.com/stevekuznetsov/avalanche-forecast/blob/2c4e79733776b013d3074fef14e2e0c89c9f8355/components/AvalancheForecastZoneMap.tsx#L498-L499

No idea why, and no idea how to detect this.

**Comment by stevekuznetsov** [comment]
Note - the `handleScroll` fires when we navigate away from the tab ...
