### ISSUE TITLE
Make "Reset the query cache" more selective

### ISSUE THREAD

**Issue by floatplane** [stevekuznetsov/avalanche-forecast#325]
Right now it blows away all of local storage, including preferences.

Would be nicer if the query cache entries were nested under a key so this delete action could be more targeted.

**Comment by stevekuznetsov** [comment]
Are we storing in separate files or directories? Maybe there's a simple file browser we can add that would allow for choosing what to delete by iterating over what's in the local dir

**Comment by floatplane** [comment]
I don't think files & directories are the right mental model, AsyncStorage is basically a [key-value store](https://react-native-async-storage.github.io/async-storage/docs/api).

It looks like `createAsyncStoragePersister` takes an optional `key` argument and can nest everything under that. Then we can change `AsyncStorage.clear()` to `AsyncStorage.removeItem(THE_MAGIC_KEY_NAME)`. I'll pick this up later today. https://github.com/stevekuznetsov/avalanche-forecast/blob/11fa07109f4e559e5073a22baec9c8a03e4d7c19/components/screens/MenuScreen.tsx#L220-L230
