### ISSUE TITLE
Select Avalanche Center (debug) menu does not scroll vertically

### ISSUE THREAD

**Issue by stevekuznetsov** [stevekuznetsov/avalanche-forecast#332]
Problem is in title.

cc @floatplane

**Comment by floatplane** [comment]
Ugh, VS Code wants to suggest imports from `tamagui` even though it's not fully working (see #337)

If this happens again then I think we should remove tamagui from `main` until we're ready to actively work on it. Maybe I can configure ESLint to warn on imports from that package.

**Comment by floatplane** [comment]
Updated #337 to add an ESLint warning for this
