### ISSUE TITLE
Upgrade to Latest Expo Version

### ISSUE THREAD

**Issue by stevekuznetsov** [stevekuznetsov/avalanche-forecast#333]
Looks like we're using the SDK version 47, but 49 is latest.

cc @floatplane 

## Update to 48 - https://github.com/stevekuznetsov/avalanche-forecast/pull/338
https://blog.expo.dev/expo-sdk-48-ccb8302e231
https://reactnative.dev/blog/2023/01/12/version-071
- [x] Update Expo
- [x] Use new `rowGap` and `columnGap` props to replace `VStack` and `HStack` logic (https://reactnative.dev/blog/2023/01/12/version-071#simplifying-layouts-with-flexbox-gap)
- [x] ~~Use new Expo Image (https://blog.expo.dev/expo-sdk-48-ccb8302e231#:~:text=Expo-,Image,-v1.0)~~
  Opened #340 to follow up on this
- [x] Remove `@types/react-native` from project

## Update to 49
https://blog.expo.dev/expo-sdk-49-c6d398cdf740
https://reactnative.dev/blog/2023/06/21/0.72-metro-package-exports-symlinks
- [x] Update Expo
- [x] Switch to Metro (if we haven't already?)
- [ ] ~~Env variable passing has changed (https://docs.expo.dev/versions/v49.0.0/config/metro/#client-environment-variables)~~
  It's unclear that this is actually necessary
- [x] Opt out of package validations where needed (https://docs.expo.dev/more/expo-cli/#configuring-dependency-validation). Will allow us to fix #339 one way or the other
- [x] `sentry-expo` major version update (https://docs.sentry.io/platforms/react-native/migration/#from-4x-to-5x) - read notes and make any changes
- [x] package renames (https://reactnative.dev/blog/2023/06/21/0.72-metro-package-exports-symlinks#package-renames)

**Comment by stevekuznetsov** [comment]
This will also require bumping React Native to 0.72

**Comment by floatplane** [comment]
started working on this...
