### ISSUE TITLE
Expired forecasts causing problems?

### ISSUE THREAD

**Issue by floatplane** [stevekuznetsov/avalanche-forecast#42]
Noticed that many regions are showing no data after 6 PM PST, possibly because of a lag between the latest NWAC forecast being published and the NAC receiving it?

Missing data:
<img width="330" alt="image" src="https://user-images.githubusercontent.com/101196/210474220-1ccf6e0c-13a2-4510-b867-f6b26663770b.png">

Also realizing that we should probably be able to display that a forecast is expired *and* that's expected, like in the Olympics:

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/101196/210474308-ba4cb632-1546-4af2-810c-b732984a6f05.png">

**Comment by floatplane** [comment]
I don't think this is necessarily expired forecasts - it seems like the data is there. But I wonder if our date filtering in `useAvalancheForecastFragment` is using dates generated in the local timezone when it should be using UTC!

**Comment by floatplane** [comment]
This does seem to be it. 6 PM PST is ~2 AM UTC so we were in different days 😬

**Comment by stevekuznetsov** [comment]
`date-fns` should have an easy fix for the timezone issue, would be good to add documentation to the hooks that makes it clear they expect UTC.

re: expired - yes! I don't know if the design has anything for that yet, I think I left a comment on Figma about that as well.
