### ISSUE TITLE
Avalanche Forecast View TODOs

### ISSUE THREAD

**Issue by stevekuznetsov** [stevekuznetsov/avalanche-forecast#45]
This is a tracking issue for follow-ups and existing issues we know need to be tackled in the forecast view.

- [x] allow collapsing each individual avalanche problem
- [ ] #111
- [x] use `date-fns` to send UTC dates to the api.avalanche.org endpoitns
  - [x] confirm with the NAC what fields or attributes of the forecast `date_start` and `date_end` select on
- [x] sync with designers & Charlotte about the "Avalanche Forecast" header
- [ ] #112
- [x] don't show horizontal divider when a card is collapsed https://github.com/stevekuznetsov/avalanche-forecast/pull/47
- [x] allow touching the entire header to collapse and open a card https://github.com/stevekuznetsov/avalanche-forecast/pull/47
- [x] add a per-avalanche-problem header
- [x] refine the forecast publication/expiration table to not require line breaks
  - [x] use a more human-friendly date format
- [x] the underline for the Avalanche/Weather/Observations tab is maybe 80% of the width of the card (or 100% of the text?) in our Figma design - looks like this PR has it as 100% of the width of the tab picker
- [x] might pre-date any work you're doing, but tapping on an image inside of an avalanche problem makes it go away forever https://github.com/stevekuznetsov/avalanche-forecast/pull/47

**Comment by floatplane** [comment]
the tapped image disappearing is all yours, @stevekuznetsov 😄. see AvalancheProblemImage

**Comment by stevekuznetsov** [comment]
:see_no_evil:

**Comment by stevekuznetsov** [comment]
The two remaining bits in here are not concretely related to the forecast view - broke them out into separate issues, closing this one.
