### ISSUE TITLE
We are playing fast and loose with dates (and maybe the API is too)

### ISSUE THREAD

**Issue by floatplane** [stevekuznetsov/avalanche-forecast#53]
Note the discrepancy here: 

forecast summary from center endpoint | forecast 
--- | ---
<img width="283" alt="image" src="https://user-images.githubusercontent.com/101196/211367035-5a7abbbc-18d7-43a3-bf17-4082afd69950.png"> | <img width="291" alt="image" src="https://user-images.githubusercontent.com/101196/211367181-72b5e731-2b0f-44c2-8b92-34ec4b160cd0.png">

The LHS is rendering UTC dates without conversion - the RHS is rendering PST. Yet AFAIK they are both going through the same dateToString conversion. _Something_ is screwed up here.

Suggestions for improvement:
- pass around Dates as much as possible, avoid using date strings everywhere. Only render to string for presentation to the user
- parse date strings in API fields to Dates, and rename fields to reflect whether they're UTC or not (i.e. `expires_date_utc: Date`)

**Comment by stevekuznetsov** [comment]
Sounds like we will have access to view the repos behind the API soon, and we should be able to get much, much more specific about what the parameters are for the API, as well as the return values, and what the expectations are around them - that should help us ensure we're doing the right thing. +100 to `Date` everywhere
