### ISSUE TITLE
Android: Avalanche Forecast Cards Rest Too Low

### ISSUE THREAD

**Issue by stevekuznetsov** [stevekuznetsov/avalanche-forecast#66]
Resting state of the cards on the map screen is too low - it doesn't show the zone name. I can still pull them up correctly, but when pushing them down they go back to resting too low. 

I'm on a Samsung Galaxy S10e

![Screenshot_20230111-163834_Expo Go](https://user-images.githubusercontent.com/7328370/211944431-5ec51814-084e-4bc4-8df8-3f044b47ee40.jpg)

**Comment by floatplane** [comment]
@stevekuznetsov are you still seeing this in recent builds?

**Comment by stevekuznetsov** [comment]
Nope!
