### ISSUE TITLE
Android: serious performance issues

### ISSUE THREAD

**Issue by floatplane** [stevekuznetsov/avalanche-forecast#68]
The Android build is seriously slow compared to the iOS build, both in the initial load phase and when transitioning to forecasts. Forecasts take ~6 seconds to load from the map view on my low-end Galaxy A02 - it's probably better on higher-powered devices, but still likely to be not great.

Turns out there's a long-running NativeBase issue (https://github.com/GeekyAnts/NativeBase/issues/4302) where other folks have bumped into performance problems with that library. Some commenters have jumped to [Tamagui](https://tamagui.dev/), which looks similar in spirit to NativeBase but is more explicitly performance-focused.

## Alternatives

_S: less than a day / M: 1-2 days / L: 1-2 weeks / XL: 1-2 months_

options | dev time (S/M/L/XL)* | pros | cons 
--- | --- | --- | ---
Stick with NativeBase, hope that the promised v4 update fixes this | S | - less churn, we focus on building out the app | - Android builds remain pretty unusable
Port to Tamagui | M | - theoretically fixes Android issues, but we haven't proved it yet<br/>- unlikely to be worse<br/>- we can throw it away if it seems non-promising, without a major detour | - takes time away from feature development<br/>- might not fix issues
Remove all frameworks and just use React Native | XL | - probably the highest possible performance <br/> - if this doesn't fix Android, nothing will | - spending dev cycles rebuilding components from scratch<br/>- takes even more time away from feature development

## Resources:
NativeBase issue: https://github.com/GeekyAnts/NativeBase/issues/4302
Tamagui launch post: https://tamagui.dev/blog/version-one
HackerNews Tamagui discussion: https://news.ycombinator.com/item?id=34186742
Tamagui Discord: https://discord.gg/4qh6tdcVDa

**Comment by floatplane** [comment]
Turns out my guess for removing NativeBase and just using React Native was waaaaaaaaay off (in a good way). We're good now!

**Comment by floatplane** [comment]
Fixed in #71, #72, #73, #74, #75

**Comment by mphill** [comment]
> Turns out my guess for removing NativeBase and just using React Native was waaaaaaaaay off (in a good way). We're good now!

What do you by this? Way off how?  I saw this issue linked on the NB issue. Just looking for some further explanation on how you addressed the performance issues. Thanks.

**Comment by stevekuznetsov** [comment]
I assume way off in the estimates of how hard it was going to be - it was a fairly small lift for this small project. By entirely removing Native Base from the project, all of our performance issues were fixed.

**Comment by mphill** [comment]
Indeed. Looking at the package.json history NativeBase was removed.

**Comment by floatplane** [comment]
@mphill I ended up writing some convenience wrappers to recreate things we used out of NativeBase (they're in https://github.com/stevekuznetsov/avalanche-forecast/tree/main/components/core). Once I had that, the process of removing NativeBase was pretty quick, not as painful as I expected. 

YMMV obviously, depends on your app and which NativeBase features you use!
