### ISSUE TITLE
handle missing forecast discussion

### ISSUE THREAD

**Issue by floatplane** [stevekuznetsov/avalanche-forecast#90]
Stevens Pass forecast issued at `Saturday, January 21, 2023 - 6:04PM` doesn't have a forecast discussion, maybe just insert a placeholder like "No forecast discussion was entered".

Doing nothing triggers warnings:

<img width="349" alt="image" src="https://user-images.githubusercontent.com/101196/213948022-249b2f61-e3b3-4b1d-98e9-539ecaca64ad.png">

**Comment by floatplane** [comment]
@charlotteguard confirmed that we should just skip the block

**Comment by stevekuznetsov** [comment]
Looks like we do this only when there's a discussion now, was fixed in my `tsc` strict mode PRs.
